const PRODUCTS=[
{id:'cafe',name:'Stanley Café-To-Go',tier:'Atractivo',quota:10,stock:8,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/cafe.webp',desc:'Premio atractivo para canje rápido.'},
{id:'aerolight',name:'Stanley Aerolight',tier:'Atractivo',quota:15,stock:8,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/aerolight.webp',desc:'Botella ligera Stanley para campañas recurrentes.'},
{id:'vitalize',name:'Stanley Vitalize Shaker',tier:'Atractivo',quota:20,stock:5,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/vitalize.webp',desc:'Premio atractivo para metas intermedias.'},
{id:'earbuds',name:'HONOR Choice Auriculares',tier:'Premium',quota:10,stock:10,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/earbuds.webp',desc:'Premio premium de alta rotación.'},
{id:'airfryer',name:'HONOR Choice Air Fryer',tier:'Premium',quota:40,stock:5,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/airfryer.webp',desc:'Premio premium para operaciones de mayor volumen.'},
{id:'robot',name:'Aspiradora Robot HONOR Choice R3',tier:'Excepcional',quota:50,stock:3,img:'https://raw.githubusercontent.com/cristopherlolimendoza-coder/APORTES-B2B/main/rewards/assets/robot.webp',desc:'Premio excepcional para cierres de mayor impacto.'}
];
const MODELS=['HONOR X5D','HONOR X6D 5G','HONOR X7e Plus','HONOR X8D','HONOR 600 E','HONOR 600 Smart','HONOR 600 5G','HONOR 600 Pro 5G','HONOR Magic 8 Lite','HONOR Magic 8 Pro'];
const KP='honor_rewards_products_v12',KR='honor_rewards_requests_v12';
let products=JSON.parse(localStorage.getItem(KP)||'null')||structuredClone(PRODUCTS);
let requests=JSON.parse(localStorage.getItem(KR)||'[]');
let current=null,filter='Todos';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KP,JSON.stringify(products));localStorage.setItem(KR,JSON.stringify(requests));}
function reserved(id){return requests.filter(r=>r.productId===id&&['En revisión','Aprobado','Entregado'].includes(r.status)).length}
function available(p){return Math.max(0,p.stock-reserved(p.id))}
function stockClass(n){return n===0?'none':n<=2?'low':'good'}
function render(){const g=$('#productGrid');g.innerHTML='';products.filter(p=>filter==='Todos'||p.tier===filter).forEach(p=>{const a=available(p),r=reserved(p.id);g.insertAdjacentHTML('beforeend',`<article class="card"><div class="cardtop"><span class="tag">${esc(p.tier)}</span><span class="stock ${stockClass(a)}">${a===0?'Agotado':'Disponible '+a}</span></div><div class="photo"><img src="${p.img}" alt="${esc(p.name)}"></div><div class="body"><h3>${esc(p.name)}</h3><p class="desc">${esc(p.desc)}</p><div class="ref">Modelo y color referencial.</div><div class="metrics"><div class="metric"><span>Cuota de canje</span><b>${p.quota} unidades</b></div><div class="metric"><span>Stock disponible</span><b>${a}</b></div><div class="metric"><span>Stock reservado</span><b>${r}</b></div></div><button class="btn primary" data-redeem="${p.id}" ${a===0?'disabled':''}>${a===0?'Sin stock':'Canjear'}</button></div></article>`)});}
$$('.filter').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
$('#productGrid').addEventListener('click',e=>{if(e.target.dataset.redeem)openRedeem(e.target.dataset.redeem)});
function modelRow(){return `<div class="modelrow"><label class="field">Modelo HONOR<select class="m-model">${MODELS.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="field">Cantidad<input class="m-qty" type="number" min="1" step="1" inputmode="numeric" placeholder="0"></label><button type="button" class="small remove remove-model">Eliminar modelo</button></div>`}
function addClient(){const div=document.createElement('div');div.className='client';div.innerHTML=`<div class="clienttop"><label class="field">RUC / RUT<input class="c-ruc" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="11" placeholder="20123456789"></label><label class="field">Razón social<input class="c-company" placeholder="Pepito SAC (ejemplo)"></label><button type="button" class="small remove remove-client">Eliminar cliente</button></div><div class="models"><div style="display:flex;justify-content:space-between;align-items:center;gap:10px"><b>Modelos del cliente</b><button type="button" class="small add-model">+ Agregar modelo</button></div><div class="models-list">${modelRow()}</div></div>`;$('#clients').appendChild(div);recalc();}
$('#addClient').onclick=addClient;
$('#clients').addEventListener('click',e=>{const c=e.target.closest('.client');if(!c)return;if(e.target.classList.contains('add-model'))c.querySelector('.models-list').insertAdjacentHTML('beforeend',modelRow());if(e.target.classList.contains('remove-model')&&c.querySelectorAll('.modelrow').length>1)e.target.closest('.modelrow').remove();if(e.target.classList.contains('remove-client')&&$$('.client').length>1)c.remove();recalc();});
$('#clients').addEventListener('input',e=>{if(e.target.classList.contains('c-ruc'))e.target.value=e.target.value.replace(/\D/g,'').slice(0,11);if(e.target.classList.contains('m-qty'))e.target.value=e.target.value.replace(/[^0-9]/g,'');recalc()});
$('#clients').addEventListener('change',recalc);$('#executive').addEventListener('input',recalc);
function collect(){return $$('.client').map(c=>({ruc:c.querySelector('.c-ruc').value.trim(),company:c.querySelector('.c-company').value.trim(),models:[...c.querySelectorAll('.modelrow')].map(r=>({model:r.querySelector('.m-model').value,qty:Number(r.querySelector('.m-qty').value)||0}))}))}
function validate(){if(!current)return'Selecciona un premio.';if(available(current)<=0)return'El premio ya no tiene stock.';if(!$('#executive').value.trim())return'Ingresa el nombre del ejecutivo.';let total=0;const clients=collect();for(let i=0;i<clients.length;i++){const c=clients[i];if(!c.ruc||!c.company)return`Completa RUC/RUT y razón social del Cliente ${i+1}.`;if(!/^\d+$/.test(c.ruc))return`El RUC/RUT del Cliente ${i+1} solo puede contener números.`;for(let j=0;j<c.models.length;j++){if(c.models[j].qty<=0)return`Ingresa una cantidad válida en Cliente ${i+1}, modelo ${j+1}.`;total+=c.models[j].qty}}if(total<current.quota)return`Faltan ${current.quota-total} unidades para alcanzar la cuota.`;return'';}
function recalc(){if(!current)return;const total=collect().reduce((s,c)=>s+c.models.reduce((x,m)=>x+m.qty,0),0);$('#total').textContent=total;$('#need').textContent=current.quota;const d=total-current.quota;$('#result').textContent=d>=0?`Cumple +${d}`:`Faltan ${Math.abs(d)}`;const err=validate();$('#submit').disabled=err!=='';$('#error').textContent=total<current.quota?`Faltan ${current.quota-total} unidades para alcanzar la cuota.`:'';}
function openRedeem(id){current=products.find(p=>p.id===id);if(!current)return;$('#productImage').src=current.img;$('#productName').textContent=current.name;$('#quota').textContent=current.quota+' uds.';$('#available').textContent=available(current);$('#reserved').textContent=reserved(current.id);$('#executive').value='';$('#channel').value='Inside Sales';$('#comment').value='';$('#clients').innerHTML='';$('#error').textContent='';$('#formView').style.display='';$('#success').classList.remove('show');addClient();$('#modal').classList.add('open');recalc();}
function close(){ $('#modal').classList.remove('open');current=null; }
$('#cancel').onclick=close;$('#closeSuccess').onclick=close;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')close()});
$('#submit').onclick=()=>{const err=validate();if(err){$('#error').textContent=err;return}const clients=collect();const totalQty=clients.reduce((s,c)=>s+c.models.reduce((x,m)=>x+m.qty,0),0);requests.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toLocaleString('es-PE'),executive:$('#executive').value.trim(),channel:$('#channel').value,productId:current.id,totalQty,clients,comment:$('#comment').value.trim(),status:'En revisión',adminNote:''});save();render();$('#formView').style.display='none';$('#success').classList.add('show');};
render();