const $=(s)=>document.querySelector(s);
let requests=[],products=[],timer=null,selectedMonth='',currentMonth='';
const esc=(s)=>String(s??'').replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
async function api(path,opt={}){const headers={'content-type':'application/json',...(opt.headers||{})};const r=await fetch(path,{...opt,credentials:'same-origin',headers,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.detail||`Error ${r.status}`);return d}
function state(s){if(s==='En revisión')return'<span class="state review">En revisión</span>';if(s==='Aprobado')return'<span class="state approved">Aprobado</span>';if(s==='Entregado')return'<span class="state delivered">Entregado</span>';return'<span class="state rejected">Rechazado</span>'}
function details(lines){if(!lines?.length)return'—';const groups={};for(const l of lines){const k=l.ruc+'|'+l.company;(groups[k]??=[]).push(l)}return Object.entries(groups).map(([k,ls])=>{const [ruc,company]=k.split('|');return `<b>${esc(company)}</b><br><span class="muted">RUC: ${esc(ruc)}</span><br>${ls.map((x)=>`${esc(x.model)}: <b>${x.qty}</b>`).join(' · ')}`}).join('<hr class="sep">')}
function filtered(){const q=($('#search')?.value||'').trim().toLowerCase(),status=$('#statusFilter')?.value||'Todos';return requests.filter((r)=>{if(status!=='Todos'&&r.status!==status)return false;if(!q)return true;return [r.cycle_month,r.executive,r.channel,r.product_name,r.status,r.comment,r.admin_note,...(r.lines||[]).flatMap((x)=>[x.ruc,x.company,x.model,x.qty])].join(' ').toLowerCase().includes(q)})}
function fillMonths(months=[]){const sel=$('#monthFilter'),prev=selectedMonth||currentMonth;sel.innerHTML='<option value="all">Todos los meses</option>';const unique=[currentMonth,...months].filter((x,i,a)=>x&&a.indexOf(x)===i);for(const m of unique)sel.insertAdjacentHTML('beforeend',`<option value="${m}">${m}${m===currentMonth?' · actual':''}</option>`);selectedMonth=prev||currentMonth;sel.value=selectedMonth;if(!sel.value){selectedMonth=currentMonth;sel.value=currentMonth}}
function markSync(){if($('#lastSync'))$('#lastSync').textContent='Última actualización: '+new Date().toLocaleTimeString('es-PE')}
async function load(){const query=selectedMonth?`?month=${encodeURIComponent(selectedMonth)}`:'';const [rq,pr]=await Promise.all([api('/api/admin/requests'+query),api('/api/admin/products')]);requests=rq.requests||[];products=pr.products||[];currentMonth=rq.currentMonth||pr.currentMonth||currentMonth;selectedMonth=rq.selectedMonth||selectedMonth||currentMonth;fillMonths(rq.months||[]);render();markSync();$('#cycleInfo').textContent=`Stock operativo: ${currentMonth}. El stock se reinicia cada mes; las cuotas pueden modificarse sin borrar el histórico.`}
async function refreshProducts(){const pr=await api('/api/admin/products');products=pr.products||[];currentMonth=pr.currentMonth||currentMonth;render();markSync()}
function render(){
  $('#kTotal').textContent=requests.length;$('#kUnits').textContent=requests.reduce((s,x)=>s+Number(x.total_qty||0),0);$('#kReview').textContent=requests.filter((x)=>x.status==='En revisión').length;$('#kApproved').textContent=requests.filter((x)=>x.status==='Aprobado').length;$('#kDelivered').textContent=requests.filter((x)=>x.status==='Entregado').length;$('#kRejected').textContent=requests.filter((x)=>x.status==='Rechazado').length;
  const view=filtered(),rows=$('#rows');rows.innerHTML='';if(!view.length)rows.innerHTML='<tr><td colspan="11" class="empty">Todavía no hay solicitudes para este filtro. La estructura ya está lista para empezar a acumular información.</td></tr>';
  for(const r of view){let acts='';if(r.status==='En revisión'){acts+=`<button class="btn success" data-act="Aprobado" data-id="${r.id}">Aprobar</button> `;acts+=`<button class="btn danger" data-act="Rechazado" data-id="${r.id}">Rechazar</button> `}else if(r.status==='Aprobado'){acts+=`<button class="btn" data-act="Entregado" data-id="${r.id}">Entregado</button> `;acts+=`<button class="btn danger" data-act="Rechazado" data-id="${r.id}">Rechazar</button> `}acts+=`<button class="btn delete" data-delete="${r.id}">Eliminar</button>`;rows.insertAdjacentHTML('beforeend',`<tr><td>${new Date(r.created_at).toLocaleString('es-PE')}</td><td>${esc(r.cycle_month||'—')}</td><td>${esc(r.executive)}</td><td>${esc(r.channel)}</td><td>${esc(r.product_name)}</td><td><b>${r.total_qty}</b></td><td>${details(r.lines)}</td><td>${esc(r.comment||'—')}</td><td>${state(r.status)}</td><td>${esc(r.admin_note||'—')}</td><td class="actionsCell">${acts}</td></tr>`)}
  const inv=$('#inventory');inv.innerHTML='';for(const p of products)inv.insertAdjacentHTML('beforeend',`<div class="inv"><h3>${esc(p.name)}</h3><div class="invstats">Disponible: <b>${p.available}</b> · En revisión: <b>${p.reserved}</b> · Aprobado: <b>${p.approved||0}</b> · Entregado: <b>${p.delivered}</b></div><div class="invgrid"><label class="field">Stock mensual<input type="number" min="0" value="${p.total_stock}" data-stock="${p.id}"></label><label class="field">Cuota de canje<input type="number" min="1" value="${p.quota}" data-quota="${p.id}"></label></div><button class="btn primary" data-save="${p.id}" style="margin-top:10px">Guardar cambios</button></div>`);
  $('#adminView').classList.remove('hidden');$('#loginView').classList.add('hidden')
}
function startTimer(){clearInterval(timer);timer=setInterval(()=>load().catch(()=>{}),30000)}
async function login(){const btn=$('#loginBtn'),err=$('#loginError'),password=$('#password').value;err.textContent='';if(!password){err.textContent='Ingresa la contraseña.';return}const old=btn.textContent;btn.disabled=true;btn.textContent='Ingresando…';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password})});$('#password').value='';await api('/api/admin/me');await load();startTimer()}catch(e){err.textContent=e.message||'No se pudo iniciar sesión.'}finally{btn.disabled=false;btn.textContent=old}}
async function boot(){try{const h=await api('/api/health');if(!h.databaseConfigured){$('#loginError').textContent='Falta vincular la base de datos D1 en Cloudflare.';return}if(!h.adminPasswordConfigured){$('#loginError').textContent='Falta configurar la contraseña de administrador en Cloudflare.';return}try{await api('/api/admin/me');await load();startTimer()}catch{}}catch(e){$('#loginError').textContent=e.message||'No se pudo validar la configuración.'}}
$('#loginBtn').addEventListener('click',login);$('#password').addEventListener('keydown',(e)=>{if(e.key==='Enter'){e.preventDefault();login()}});$('#search').addEventListener('input',render);$('#statusFilter').addEventListener('change',render);$('#monthFilter').addEventListener('change',async(e)=>{selectedMonth=e.target.value;await load().catch((err)=>alert(err.message))});$('#refreshBtn').onclick=()=>load().catch((e)=>alert(e.message));
$('#logoutBtn').onclick=async()=>{clearInterval(timer);await api('/api/admin/logout',{method:'POST'}).catch(()=>{});location.reload()};
$('#rows').addEventListener('click',async(e)=>{const act=e.target.closest('[data-act]'),del=e.target.closest('[data-delete]');if(act){let note='';if(act.dataset.act==='Rechazado'){note=prompt('Motivo / observación del rechazo:','');if(note===null)return}const old=act.textContent;act.disabled=true;act.textContent=act.dataset.act==='Aprobado'?'Aprobando…':act.dataset.act==='Entregado'?'Guardando…':'Rechazando…';try{await api('/api/admin/status',{method:'POST',body:JSON.stringify({id:act.dataset.id,status:act.dataset.act,note})});const r=requests.find((x)=>x.id===act.dataset.id);if(r){r.status=act.dataset.act;r.admin_note=note}render();await refreshProducts()}catch(err){alert(err.message);act.disabled=false;act.textContent=old}}if(del){if(!confirm('¿Eliminar definitivamente esta solicitud del histórico?'))return;const old=del.textContent;del.disabled=true;del.textContent='Eliminando…';try{await api('/api/admin/delete',{method:'POST',body:JSON.stringify({id:del.dataset.delete})});requests=requests.filter((x)=>x.id!==del.dataset.delete);render();await refreshProducts()}catch(err){alert(err.message);del.disabled=false;del.textContent=old}}});
$('#inventory').addEventListener('click',async(e)=>{const b=e.target.closest('[data-save]');if(!b)return;const id=b.dataset.save,stock=$(`[data-stock="${id}"]`),quota=$(`[data-quota="${id}"]`),old=b.textContent;b.disabled=true;b.textContent='Guardando…';try{await api('/api/admin/product',{method:'POST',body:JSON.stringify({id,total_stock:Number(stock.value),quota:Number(quota.value)})});await refreshProducts()}catch(err){alert(err.message);b.disabled=false;b.textContent=old}});
async function resetMonth(){if(!confirm('Esto restablecerá únicamente el STOCK del mes actual al stock mensual configurado. No cambiará las cuotas y no borrará el histórico de solicitudes. ¿Continuar?'))return;const b=$('#resetBtn'),old=b.textContent;b.disabled=true;b.textContent='Restableciendo…';try{const d=await api('/api/admin/reset-month',{method:'POST',body:'{}'});await refreshProducts();alert(d.message||'Stock del mes restablecido correctamente.')}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent=old}}
$('#resetBtn').onclick=resetMonth;
function excelRows(){const view=filtered(),out=[['Fecha','Mes','Ejecutivo','Canal','Premio','Unidades reportadas','Estado','Comentario FFVV','Observación admin','RUC','Razón social','Modelo','Cantidad']];for(const r of view){if(!(r.lines||[]).length)out.push([r.created_at,r.cycle_month,r.executive,r.channel,r.product_name,r.total_qty,r.status,r.comment||'',r.admin_note||'','','','','']);for(const l of(r.lines||[]))out.push([r.created_at,r.cycle_month,r.executive,r.channel,r.product_name,r.total_qty,r.status,r.comment||'',r.admin_note||'',l.ruc,l.company,l.model,l.qty])}return out}
function downloadExcel(){const rows=excelRows(),html='<!doctype html><html><head><meta charset="utf-8"></head><body><table>'+rows.map((r,i)=>'<tr>'+r.map((v)=>`<${i?'td':'th'}>${esc(v)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></body></html>',blob=new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`HONOR_Rewards_${selectedMonth||currentMonth||'historico'}.xls`;a.click();URL.revokeObjectURL(url)}
$('#exportBtn').onclick=downloadExcel;$('#exportBottomBtn').onclick=downloadExcel;boot();